import { brand } from '@/assets/branding';

export const PRIVACY_POLICY_EFFECTIVE_DATE = 'July 5, 2026';

export type PrivacyPolicySection = {
  title: string;
  paragraphs: string[];
  bullets?: string[];
};

export const PRIVACY_POLICY_INTRO = `Thank you for using ${brand.name} ("the App"). Your privacy is important to us. This Privacy Policy explains how the App handles your information.`;

export const PRIVACY_POLICY_SECTIONS: PrivacyPolicySection[] = [
  {
    title: '1. Information We Collect',
    paragraphs: [
      `${brand.name} is designed to work entirely on your device.`,
      'The App does not collect, transmit, or store your personal information on external servers.',
      'Passwords generated by the App remain on your device unless you choose to copy, export, or share them.',
    ],
  },
  {
    title: '2. Password Storage',
    paragraphs: [
      'If you choose to save generated passwords or preferences, they are stored locally on your device using secure local storage.',
      'Your saved data is not uploaded to any cloud service or external server by the App.',
    ],
  },
  {
    title: '3. Internet Connection',
    paragraphs: [
      `${brand.name} does not require an internet connection to generate passwords or use its core features.`,
    ],
  },
  {
    title: '4. Permissions',
    paragraphs: [
      'Depending on the features you use, the App may request the following permissions:',
    ],
    bullets: [
      'Storage Access: Used only if you choose to export password history or save generated files.',
      'No permission is requested unless it is required for a feature you actively use.',
    ],
  },
  {
    title: '5. Data Sharing',
    paragraphs: [
      'We do not sell, rent, or share your personal information with third parties.',
      'Your generated passwords and saved data remain under your control.',
    ],
  },
  {
    title: '6. Analytics',
    paragraphs: [
      `The current version of ${brand.name} does not collect analytics or usage data.`,
      'If analytics are added in a future version, this Privacy Policy will be updated accordingly.',
    ],
  },
  {
    title: '7. Third-Party Services',
    paragraphs: [
      'The App may use standard Android or iOS system services to support functionality such as sharing exported files.',
      'If future versions include third-party services (such as crash reporting or analytics), this Privacy Policy will be updated to describe those services.',
    ],
  },
  {
    title: '8. Data Security',
    paragraphs: [
      'We take reasonable measures to protect your locally stored data. However, no method of electronic storage is completely secure.',
      'You are responsible for keeping your device protected with appropriate security measures such as a PIN, password, or biometric authentication.',
    ],
  },
  {
    title: "9. Children's Privacy",
    paragraphs: [
      `${brand.name} is not directed toward children under the age of 13. The App does not knowingly collect personal information from children.`,
    ],
  },
  {
    title: '10. Changes to This Privacy Policy',
    paragraphs: [
      'We may update this Privacy Policy from time to time. Any changes will be reflected by updating the Effective Date at the top of this document.',
      'We will make reasonable efforts to respond to your inquiry.',
    ],
  },
];
